/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Yash
 */
public class ConfirmationDialogBox extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmationDialogBox
     */
    private ArrayList<List> Items = new ArrayList();
    private String userID = "";
    
    public ConfirmationDialogBox() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    public ConfirmationDialogBox(ArrayList<List> TableContents, String s) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        userID = s;
        Object ob[][] = new Object[10][4];
        for (List table_Row: TableContents){
            int i = TableContents.indexOf(table_Row);
            Object ob1[] = {TableContents.get(i).get(2).toString(), TableContents.get(i).get(3).toString(), TableContents.get(i).get(4).toString(), TableContents.get(i).get(5).toString()};
            ob[i] = ob1;
        }
        medContentsTable.setModel(new DefaultTableModel(ob, new String [] {
            "Medicine Name", "Medicine Group", "Company Name", "Quantity"
        }));
        medContentsTable.getTableHeader().setDefaultRenderer(new TableHeaderFont());
        medContentsTable.setShowGrid(true);
        medContentsTable.setGridColor(Color.BLACK);
        
        Items = TableContents;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medContentsTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        genBtn = new javax.swing.JButton();
        addMoreBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(226, 226, 226)));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 300));

        medContentsTable.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        medContentsTable.setForeground(new java.awt.Color(248, 30, 154));
        medContentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Medicine Group", "Company Name", "Quantity"
            }
        ));
        medContentsTable.setFillsViewportHeight(true);
        medContentsTable.setRowHeight(40);
        jScrollPane1.setViewportView(medContentsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        genBtn.setBackground(new java.awt.Color(248, 30, 154));
        genBtn.setFont(new java.awt.Font("Rubik", 1, 20)); // NOI18N
        genBtn.setForeground(new java.awt.Color(255, 255, 255));
        genBtn.setText("Generate Bill");
        genBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(248, 30, 154)));
        genBtn.setContentAreaFilled(false);
        genBtn.setOpaque(true);
        genBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genBtnMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        jPanel4.add(genBtn, gridBagConstraints);

        addMoreBtn.setBackground(new java.awt.Color(248, 30, 154));
        addMoreBtn.setFont(new java.awt.Font("Rubik", 1, 20)); // NOI18N
        addMoreBtn.setForeground(new java.awt.Color(255, 255, 255));
        addMoreBtn.setText("Add more +");
        addMoreBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(248, 30, 154)));
        addMoreBtn.setContentAreaFilled(false);
        addMoreBtn.setOpaque(true);
        addMoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMoreBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMoreBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMoreBtnMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(0, 120, 40, 0);
        jPanel4.add(addMoreBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 790, 580);

        setSize(new java.awt.Dimension(826, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoreBtnMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_addMoreBtnMouseClicked

    private void genBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genBtnMouseClicked
        // TODO add your handling code here:
        dispose();
        new BillGenFormModel(Items, "1").setVisible(true);    // for testing default value is kept UserID : 1
    }//GEN-LAST:event_genBtnMouseClicked

    private void addMoreBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoreBtnMouseEntered
        // TODO add your handling code here:
        addMoreBtn.setForeground(Color.decode("#F81E9A"));
        addMoreBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_addMoreBtnMouseEntered

    private void addMoreBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMoreBtnMouseExited
        // TODO add your handling code here:
        addMoreBtn.setForeground(Color.WHITE);
        addMoreBtn.setBackground(Color.decode("#F81E9A"));
    }//GEN-LAST:event_addMoreBtnMouseExited

    private void genBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genBtnMouseEntered
        // TODO add your handling code here:
        genBtn.setForeground(Color.decode("#F81E9A"));
        genBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_genBtnMouseEntered

    private void genBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genBtnMouseExited
        // TODO add your handling code here:
        genBtn.setForeground(Color.WHITE);
        genBtn.setBackground(Color.decode("#F81E9A"));
    }//GEN-LAST:event_genBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationDialogBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoreBtn;
    private javax.swing.JButton genBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medContentsTable;
    // End of variables declaration//GEN-END:variables
}
