/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Color;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author Yash
 */
public class Login_form extends javax.swing.JFrame {

    /**
     * Creates new form Login_form
     */
    Color gray = Color.decode("#999999");
    Color pink = Color.decode("#F81E9A");
    public Login_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_loginText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass_loginText = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        register_hyperlink = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        useOtp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 440));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(248, 30, 154));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 140));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 140));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(248, 30, 154));
        jTextField2.setFont(new java.awt.Font("Liberation Sans", 1, 55)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("MediGo");
        jTextField2.setBorder(null);
        jTextField2.setMinimumSize(new java.awt.Dimension(198, 74));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jTextField2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1920, 940));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 940));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 40)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(248, 30, 154));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Login");
        jTextField1.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField1, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 30, 154));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 20, -30);
        jPanel4.add(jLabel1, gridBagConstraints);

        username_loginText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        username_loginText.setForeground(new java.awt.Color(153, 153, 153));
        username_loginText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username_loginText.setText("Enter your username");
        username_loginText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        username_loginText.setPreferredSize(new java.awt.Dimension(306, 47));
        username_loginText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_loginTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_loginTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -30);
        jPanel4.add(username_loginText, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 30, 154));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(143, 41));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 250, 20, -30);
        jPanel4.add(jLabel2, gridBagConstraints);

        pass_loginText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        pass_loginText.setForeground(new java.awt.Color(153, 153, 153));
        pass_loginText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_loginText.setText("Enter pass");
        pass_loginText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        pass_loginText.setPreferredSize(new java.awt.Dimension(306, 47));
        pass_loginText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_loginTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_loginTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -30);
        jPanel4.add(pass_loginText, gridBagConstraints);

        login_button.setBackground(new java.awt.Color(255, 255, 255));
        login_button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 27)); // NOI18N
        login_button.setForeground(new java.awt.Color(248, 30, 154));
        login_button.setText("Login");
        login_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(248, 30, 154), new java.awt.Color(248, 30, 154)));
        login_button.setContentAreaFilled(false);
        login_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login_button.setMaximumSize(new java.awt.Dimension(65, 43));
        login_button.setMinimumSize(new java.awt.Dimension(65, 43));
        login_button.setPreferredSize(new java.awt.Dimension(65, 43));
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_buttonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel4.add(login_button, gridBagConstraints);

        register_hyperlink.setEditable(false);
        register_hyperlink.setBackground(new java.awt.Color(255, 255, 255));
        register_hyperlink.setFont(new java.awt.Font("Liberation Sans", 3, 12)); // NOI18N
        register_hyperlink.setForeground(new java.awt.Color(248, 30, 154));
        register_hyperlink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        register_hyperlink.setText("Don't have an account? Register NOW!");
        register_hyperlink.setAutoscrolls(false);
        register_hyperlink.setBorder(null);
        register_hyperlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_hyperlinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_hyperlinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_hyperlinkMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, -30, 20, -30);
        jPanel4.add(register_hyperlink, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 14;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Liberation Sans", 2, 20)); // NOI18N
        jCheckBox1.setText("Hide");
        jCheckBox1.setBorder(null);
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.setMaximumSize(new java.awt.Dimension(83, 30));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(83, 30));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(83, 30));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 20, 0);
        jPanel4.add(jCheckBox1, gridBagConstraints);

        useOtp.setEditable(false);
        useOtp.setBackground(new java.awt.Color(255, 255, 255));
        useOtp.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        useOtp.setForeground(new java.awt.Color(248, 30, 154));
        useOtp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        useOtp.setText("Forgot Password? Use OTP");
        useOtp.setBorder(null);
        useOtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                useOtpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                useOtpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                useOtpMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(-10, 0, 20, 0);
        jPanel4.add(useOtp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        jPanel3.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 4.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_hyperlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_hyperlinkMouseClicked
        // TODO add your handling code here:
        Signup_form reg = new Signup_form();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_register_hyperlinkMouseClicked

    private void register_hyperlinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_hyperlinkMouseEntered
        // TODO add your handling code here:
        register_hyperlink.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_register_hyperlinkMouseEntered

    private void register_hyperlinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_hyperlinkMouseExited
        // TODO add your handling code here:
        register_hyperlink.setForeground(pink);
    }//GEN-LAST:event_register_hyperlinkMouseExited

    private void login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseEntered
        // TODO add your handling code here:
        Border bd = BorderFactory.createLineBorder(pink, 3, true);
        login_button.setBorder(bd);
    }//GEN-LAST:event_login_buttonMouseEntered

    private void login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseExited
        // TODO add your handling code here:
        login_button.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), pink));
    }//GEN-LAST:event_login_buttonMouseExited

    private void username_loginTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_loginTextFocusGained
        // TODO add your handling code here:
        if(username_loginText.getText().equals("Enter your username")){
            username_loginText.setText("");
        }
        username_loginText.setForeground(Color.BLACK);
    }//GEN-LAST:event_username_loginTextFocusGained

    private void pass_loginTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_loginTextFocusGained
        // TODO add your handling code here:
        if(pass_loginText.getText().equals("Enter pass")){
            pass_loginText.setText("");
        }
        pass_loginText.setForeground(Color.BLACK);
    }//GEN-LAST:event_pass_loginTextFocusGained

    private void username_loginTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_loginTextFocusLost
        // TODO add your handling code here:
        if(username_loginText.getText().equals("")){
            username_loginText.setText("Enter your username");
            username_loginText.setForeground(gray);
        }
    }//GEN-LAST:event_username_loginTextFocusLost

    private void pass_loginTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_loginTextFocusLost
        // TODO add your handling code here:
        if(pass_loginText.getText().equals("")){
            pass_loginText.setText("Enter pass");
            pass_loginText.setForeground(gray);
        }
    }//GEN-LAST:event_pass_loginTextFocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        String pass = pass_loginText.getText();
        if(jCheckBox1.isSelected()){
            if(pass.equals("") || pass.equals("Enter pass")){
                pass_loginText.setText("Enter pass");
                jCheckBox1.setSelected(false);
            } else {
                pass_loginText.setEchoChar((char)0);
                jCheckBox1.setText("Show");
            }
        } else {
            jCheckBox1.setText("Hide");
            pass_loginText.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void useOtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useOtpMouseClicked
        // TODO add your handling code here:
        dispose();
        OTP_Login otp = new OTP_Login();
        otp.setVisible(true);

    }//GEN-LAST:event_useOtpMouseClicked

    private void useOtpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useOtpMouseEntered
        // TODO add your handling code here:
        useOtp.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_useOtpMouseEntered

    private void useOtpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useOtpMouseExited
        // TODO add your handling code here:
        useOtp.setForeground(pink);
    }//GEN-LAST:event_useOtpMouseExited
    
    public static String verifyPass(String p, byte[] salt){
        String h_pass = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(salt);
            byte[] bytes = md.digest(p.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            h_pass = sb.toString();
            
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        return h_pass;
    }
    
    public int countTimes = 3;
    private String attemptsLeft(){
        return String.valueOf(countTimes--);
    }
    
    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
        // TODO add your handling code here:
        String username = username_loginText.getText();
        String password = String.valueOf(pass_loginText.getPassword());
        
        if(username.length() > 0 && password.length() > 0){
            try{
                
                String url = "jdbc:mysql://localhost:3306/medical_system?autoReconnect=true&useSSL=false";
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection(url, "root", "");
                Statement st = conn.createStatement();
                
                String userID = "";
                String salt = null;
                String originalPass = null;
                ResultSet rs = st.executeQuery("Select `User ID`, Salt, Pass from user_table where Username='"+username+"'");
                
                if(countTimes == 0){
                    countTimes=3;
                    new Invalid_user_pass("0").setVisible(true);
                    new java.util.Timer().schedule(
                        new java.util.TimerTask() {
                            @Override
                            public void run() {
                                dispose(); // closes login window
                            }
                        }, 1500
                    );
                } else {
                    if(rs.next()){
                        userID = rs.getString("User ID");
                        salt = rs.getString("Salt");
                        originalPass = rs.getString("Pass");
                    } else {
                        Invalid_user_pass IUP = new Invalid_user_pass(attemptsLeft());
                        IUP.setVisible(true);
                    }

                    String currentPass = verifyPass(password, new BigInteger(salt, 2).toByteArray());

                    if(currentPass.equals(originalPass)){
                        dispose();
                        new Home(userID).setVisible(true);
                        LoggedInDialogBox LIDB = new LoggedInDialogBox();
                        LIDB.setVisible(true);
                    } else { 
                        Invalid_user_pass IUP = new Invalid_user_pass(attemptsLeft());
                        IUP.setVisible(true);
                    }
                }
                
                conn.close();
                
            } catch (ClassNotFoundException classNotFoundException) {
            } catch (SQLException sQLException) {
            }
        }
    }//GEN-LAST:event_login_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField pass_loginText;
    private javax.swing.JTextField register_hyperlink;
    private javax.swing.JTextField useOtp;
    private javax.swing.JTextField username_loginText;
    // End of variables declaration//GEN-END:variables
}
