/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import static classes.Login_form.verifyPass;
import java.awt.Color;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Timer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author Yash
 */
public class OTP_Login extends javax.swing.JFrame {

    /**
     * Creates new form OTP_Login
     */
    public int number;
    Color gray = Color.decode("#999999");
    public OTP_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OTP_text = new javax.swing.JTextField();
        sendOtp = new javax.swing.JButton();
        login = new javax.swing.JButton();
        login_with_pass = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        timeOverClock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(248, 30, 154));
        jTextField1.setFont(new java.awt.Font("Liberation Sans", 1, 55)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MediGo");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(1920, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 85;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jTextField1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 40)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(248, 30, 154));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Login with OTP");
        jTextField4.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jTextField4, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 30, 154));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Email");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(143, 41));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 160, 20, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        mailText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        mailText.setForeground(new java.awt.Color(153, 153, 153));
        mailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailText.setText("Enter your email address");
        mailText.setToolTipText("Enter your email address here");
        mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mailText.setPreferredSize(new java.awt.Dimension(354, 47));
        mailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, -230, 20, 0);
        jPanel2.add(mailText, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 30, 154));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("OTP");
        jLabel2.setPreferredSize(new java.awt.Dimension(143, 41));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 160, 20, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        OTP_text.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        OTP_text.setForeground(new java.awt.Color(153, 153, 153));
        OTP_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OTP_text.setText("Enter your 6-digit OTP");
        OTP_text.setToolTipText("Enter your 6-digit OTP here");
        OTP_text.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        OTP_text.setPreferredSize(new java.awt.Dimension(354, 47));
        OTP_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OTP_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                OTP_textFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, -230, 20, 0);
        jPanel2.add(OTP_text, gridBagConstraints);

        sendOtp.setBackground(new java.awt.Color(255, 255, 255));
        sendOtp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 27)); // NOI18N
        sendOtp.setForeground(new java.awt.Color(248, 30, 154));
        sendOtp.setText("Send OTP");
        sendOtp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(248, 30, 154), new java.awt.Color(248, 30, 154)));
        sendOtp.setContentAreaFilled(false);
        sendOtp.setOpaque(true);
        sendOtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendOtpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendOtpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendOtpMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, -350);
        jPanel2.add(sendOtp, gridBagConstraints);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 27)); // NOI18N
        login.setForeground(new java.awt.Color(248, 30, 154));
        login.setText("Login");
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(248, 30, 154), new java.awt.Color(248, 30, 154)));
        login.setContentAreaFilled(false);
        login.setOpaque(true);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(25, -190, 0, 0);
        jPanel2.add(login, gridBagConstraints);

        login_with_pass.setBackground(new java.awt.Color(248, 30, 154));
        login_with_pass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        login_with_pass.setForeground(new java.awt.Color(255, 255, 255));
        login_with_pass.setText("<< Login with password");
        login_with_pass.setAutoscrolls(true);
        login_with_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 30, 154), 4, true));
        login_with_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_with_passMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_with_passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_with_passMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 20, 20);
        jPanel2.add(login_with_pass, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 5.0;
        jPanel2.add(jPanel4, gridBagConstraints);

        timeOverClock.setFont(new java.awt.Font("Rubik", 1, 13)); // NOI18N
        timeOverClock.setForeground(new java.awt.Color(255, 51, 51));
        timeOverClock.setBorder(null);
        timeOverClock.setPreferredSize(new java.awt.Dimension(100, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        jPanel2.add(timeOverClock, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 4.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTextFocusGained
        // TODO add your handling code here:
        if(mailText.getText().equals("Enter your email address") || mailText.getText().equals("Invalid Email !")){
            mailText.setText("");
        }
        mailText.setForeground(Color.BLACK);;
    }//GEN-LAST:event_mailTextFocusGained

    private void OTP_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OTP_textFocusGained
        // TODO add your handling code here:
        if(OTP_text.getText().equals("Enter your 6-digit OTP")){
            OTP_text.setText("");
        }
        OTP_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_OTP_textFocusGained

    private void mailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTextFocusLost
        // TODO add your handling code here:
        if(mailText.getText().equals("")){
            mailText.setText("Enter your email address");
            mailText.setForeground(gray);
        }
    }//GEN-LAST:event_mailTextFocusLost

    private void OTP_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OTP_textFocusLost
        // TODO add your handling code here:
        if(OTP_text.getText().equals("")){
            OTP_text.setText("Enter your 6-digit OTP");
            OTP_text.setForeground(gray);
        }
    }//GEN-LAST:event_OTP_textFocusLost

    private void genOTP(){
        Pattern pattern = Pattern.compile("^(.+)@(.+)$");
        Matcher matcher = pattern.matcher(mailText.getText());
        if(!matcher.matches()){
                mailText.setText("Invalid Email !");
                mailText.setForeground(Color.RED);
        } else {
            timeOverClock.setText("00:40");
            Random r = new Random();
            number = r.nextInt(999999);
            Codewind.Send.mail("demodanger8@gmail.com", mailText.getText(), "1234567890@0", "OTP from MediGo", "Your OTP is "+Integer.toString(number));  
        }
    }
    
    
    Timer timer = new Timer();
    private void sendOtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseClicked
        // TODO add your handling code here:
        genOTP();   //insatntiate Timer class
        timer.scheduleAtFixedRate(
                new java.util.TimerTask(){
                    public void run(){
                        String strTimer = timeOverClock.getText();
                        if(strTimer.equals("00:00")){
                            number=0;
                            timeOverClock.setText("");
                            OTP_ExpiredDialogBox OEDB = new OTP_ExpiredDialogBox();
                            OEDB.setVisible(true);
                            timer.cancel();
                        } else {
                            int sec = Integer.valueOf(strTimer.split(":")[1])-1; 
                            timeOverClock.setText(String.join(":", strTimer.split(":")[0], sec<10 ? "0"+String.valueOf(sec) : String.valueOf(sec)));
                        }
                    }
                },
                0, //delay
                1000  //repeat after 1s
        );
    }//GEN-LAST:event_sendOtpMouseClicked

    private void login_with_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_with_passMouseClicked
        // TODO add your handling code here:
        dispose();
        Login_form logf = new Login_form();
        logf.setVisible(true);
    }//GEN-LAST:event_login_with_passMouseClicked

    private void sendOtpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseEntered
        // TODO add your handling code here:
        Border bd = BorderFactory.createLineBorder(Color.decode("#F81E9A"), 3, true);
        sendOtp.setBorder(bd);
    }//GEN-LAST:event_sendOtpMouseEntered

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
        Border bd = BorderFactory.createLineBorder(Color.decode("#F81E9A"), 3, true);
        login.setBorder(bd);
    }//GEN-LAST:event_loginMouseEntered

    private void sendOtpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseExited
        // TODO add your handling code here:
        sendOtp.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#F81E9A")));
    }//GEN-LAST:event_sendOtpMouseExited

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
        login.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#F81E9A")));
    }//GEN-LAST:event_loginMouseExited

    private void login_with_passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_with_passMouseEntered
        // TODO add your handling code here:
        login_with_pass.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#999999")));
        login_with_pass.setForeground(Color.decode("#F81E9A"));
        login_with_pass.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_login_with_passMouseEntered

    private void login_with_passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_with_passMouseExited
        // TODO add your handling code here:
        login_with_pass.setBorder(BorderFactory.createLineBorder(Color.decode("#F81E9A"), 4, true));
        login_with_pass.setForeground(Color.decode("#ffffff"));
        login_with_pass.setBackground(Color.decode("#F81E9A"));
    }//GEN-LAST:event_login_with_passMouseExited
    
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        if(OTP_text.getText().equals(Integer.toString(number))){
            timer.cancel(); //Clases Timer class's instance named timer
            String userID = "";
            try{
                
                String url = "jdbc:mysql://localhost:3306/medical_system?autoReconnect=true&useSSL=false";
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection(url, "root", "");
                Statement st = conn.createStatement();
                
                ResultSet rs = st.executeQuery("Select `User ID` from user_table where Email='"+mailText.getText()+"'");
                if(rs.next()){
                    userID = rs.getString("User ID");
                }
  
                conn.close();
            } catch (Exception e){
                System.out.println(e);
            }
            dispose();
            //Popup on successful login
            new Home(userID).setVisible(true);
            AccountVerifiedDialogBox AD = new AccountVerifiedDialogBox();
            AD.setVisible(true);
        } else {
            Invalid_OTP io = new Invalid_OTP();
            io.setVisible(true);
        }
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTP_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTP_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTP_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTP_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTP_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OTP_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton login;
    private javax.swing.JButton login_with_pass;
    private javax.swing.JTextField mailText;
    private javax.swing.JButton sendOtp;
    private javax.swing.JTextField timeOverClock;
    // End of variables declaration//GEN-END:variables
}
