/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Color;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.SoftBevelBorder;
import Codewind.Send;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yash
 */
public class Signup_form extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_form
     */
    public int number;
    Color gray = Color.decode("#999999");
    public Signup_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_nameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mob_no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        OTP_text = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_nameAddr = new javax.swing.JTextArea();
        signUp_button = new javax.swing.JButton();
        goToLogin_button = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        sendOtp = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        timeOverClock = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        GSTNO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(248, 30, 154));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 140));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 140));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(248, 30, 154));
        jTextField1.setFont(new java.awt.Font("Liberation Sans", 1, 55)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MediGo");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1920, 940));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 940));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 40)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(248, 30, 154));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Register");
        jTextField2.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField2, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 30, 154));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, -30, 20, -50);
        jPanel6.add(jLabel1, gridBagConstraints);

        nameText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        nameText.setForeground(new java.awt.Color(153, 153, 153));
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setText("Enter your full name");
        nameText.setToolTipText("Enter your name here");
        nameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        nameText.setMinimumSize(new java.awt.Dimension(370, 47));
        nameText.setPreferredSize(new java.awt.Dimension(370, 47));
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, -80, 20, -30);
        jPanel6.add(nameText, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 30, 154));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Email");
        jLabel2.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel2, gridBagConstraints);

        mailText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        mailText.setForeground(new java.awt.Color(153, 153, 153));
        mailText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailText.setText("Enter your email address");
        mailText.setToolTipText("Enter your email address heere");
        mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        mailText.setMinimumSize(new java.awt.Dimension(370, 47));
        mailText.setPreferredSize(new java.awt.Dimension(370, 47));
        mailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(mailText, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 30, 154));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Company Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel3, gridBagConstraints);

        c_nameText.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        c_nameText.setForeground(new java.awt.Color(153, 153, 153));
        c_nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_nameText.setText("Enter your company's name");
        c_nameText.setToolTipText("Enter your company's name here");
        c_nameText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        c_nameText.setMinimumSize(new java.awt.Dimension(370, 47));
        c_nameText.setPreferredSize(new java.awt.Dimension(370, 47));
        c_nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_nameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_nameTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(c_nameText, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 30, 154));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Company's Address");
        jLabel4.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel4, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 30, 154));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Mobile Number");
        jLabel5.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel5, gridBagConstraints);

        mob_no.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        mob_no.setForeground(new java.awt.Color(153, 153, 153));
        mob_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mob_no.setText("Enter your mobile number");
        mob_no.setToolTipText("Enter your mobile number here");
        mob_no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        mob_no.setMinimumSize(new java.awt.Dimension(370, 47));
        mob_no.setPreferredSize(new java.awt.Dimension(370, 47));
        mob_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mob_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mob_noFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(mob_no, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 30, 154));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Username");
        jLabel6.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel6, gridBagConstraints);

        username.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Enter your username");
        username.setToolTipText("Enter a username that you wish");
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        username.setMinimumSize(new java.awt.Dimension(370, 47));
        username.setPreferredSize(new java.awt.Dimension(370, 47));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(username, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(248, 30, 154));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Password");
        jLabel7.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel7, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(248, 30, 154));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("OTP");
        jLabel8.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel8, gridBagConstraints);

        OTP_text.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        OTP_text.setForeground(new java.awt.Color(153, 153, 153));
        OTP_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OTP_text.setText("Enter your 6-digit OTP");
        OTP_text.setToolTipText("Enter OTP sent to your email address");
        OTP_text.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        OTP_text.setMinimumSize(new java.awt.Dimension(370, 47));
        OTP_text.setPreferredSize(new java.awt.Dimension(370, 47));
        OTP_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OTP_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                OTP_textFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(OTP_text, gridBagConstraints);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(370, 130));
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(370, 130));

        c_nameAddr.setColumns(20);
        c_nameAddr.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        c_nameAddr.setForeground(new java.awt.Color(153, 153, 153));
        c_nameAddr.setLineWrap(true);
        c_nameAddr.setRows(5);
        c_nameAddr.setText("Enter company's address");
        c_nameAddr.setToolTipText("Enter company's address here");
        c_nameAddr.setWrapStyleWord(true);
        c_nameAddr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        c_nameAddr.setMinimumSize(new java.awt.Dimension(444, 184));
        c_nameAddr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c_nameAddrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c_nameAddrFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(c_nameAddr);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(jScrollPane2, gridBagConstraints);

        signUp_button.setBackground(new java.awt.Color(255, 255, 255));
        signUp_button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 27)); // NOI18N
        signUp_button.setForeground(new java.awt.Color(248, 30, 154));
        signUp_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(248, 30, 154), new java.awt.Color(248, 30, 154)));
        signUp_button.setContentAreaFilled(false);
        signUp_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUp_button.setLabel("Sign Up");
        signUp_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUp_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUp_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUp_buttonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, -150, 0, 0);
        jPanel6.add(signUp_button, gridBagConstraints);

        goToLogin_button.setBackground(new java.awt.Color(248, 30, 154));
        goToLogin_button.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        goToLogin_button.setForeground(new java.awt.Color(255, 255, 255));
        goToLogin_button.setText("<< Go back to login");
        goToLogin_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 30, 154), 4, true));
        goToLogin_button.setPreferredSize(new java.awt.Dimension(209, 43));
        goToLogin_button.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goToLogin_buttonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                goToLogin_buttonFocusLost(evt);
            }
        });
        goToLogin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToLogin_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goToLogin_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goToLogin_buttonMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel6.add(goToLogin_button, gridBagConstraints);

        passField.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField.setText("Enter pass");
        passField.setToolTipText("Enter your password here");
        passField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        passField.setMinimumSize(new java.awt.Dimension(370, 47));
        passField.setPreferredSize(new java.awt.Dimension(370, 47));
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(passField, gridBagConstraints);

        sendOtp.setBackground(new java.awt.Color(255, 255, 255));
        sendOtp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 27)); // NOI18N
        sendOtp.setForeground(new java.awt.Color(248, 30, 154));
        sendOtp.setText("Send OTP");
        sendOtp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(248, 30, 154), new java.awt.Color(248, 30, 154)));
        sendOtp.setContentAreaFilled(false);
        sendOtp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sendOtp.setMaximumSize(new java.awt.Dimension(203, 43));
        sendOtp.setMinimumSize(new java.awt.Dimension(203, 43));
        sendOtp.setOpaque(true);
        sendOtp.setPreferredSize(new java.awt.Dimension(203, 43));
        sendOtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendOtpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendOtpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendOtpMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, -250);
        jPanel6.add(sendOtp, gridBagConstraints);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Liberation Sans", 2, 20)); // NOI18N
        jCheckBox1.setText("Hide");
        jCheckBox1.setBorder(null);
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.setMaximumSize(new java.awt.Dimension(83, 30));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(83, 30));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(83, 30));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = -10;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 20, 0);
        jPanel6.add(jCheckBox1, gridBagConstraints);

        timeOverClock.setBackground(new java.awt.Color(255, 255, 255));
        timeOverClock.setFont(new java.awt.Font("Rubik", 1, 15)); // NOI18N
        timeOverClock.setForeground(new java.awt.Color(255, 51, 51));
        timeOverClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 20, 0);
        jPanel6.add(timeOverClock, gridBagConstraints);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(248, 30, 154));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("GST Number");
        jLabel9.setPreferredSize(new java.awt.Dimension(306, 47));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -30, 20, -50);
        jPanel6.add(jLabel9, gridBagConstraints);

        GSTNO.setFont(new java.awt.Font("Segoe UI Light", 1, 26)); // NOI18N
        GSTNO.setForeground(new java.awt.Color(153, 153, 153));
        GSTNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GSTNO.setText("Enter your GST number");
        GSTNO.setToolTipText("Enter your GST number here");
        GSTNO.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        GSTNO.setMinimumSize(new java.awt.Dimension(370, 47));
        GSTNO.setPreferredSize(new java.awt.Dimension(370, 47));
        GSTNO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GSTNOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GSTNOFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -80, 20, -30);
        jPanel6.add(GSTNO, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        jPanel3.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 4.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusGained
        // TODO add your handling code here:
        if(nameText.getText().equals("Enter your full name") || nameText.getText().equals("Invalid Name !")){
            nameText.setText("");
        }
        nameText.setForeground(Color.BLACK);
    }//GEN-LAST:event_nameTextFocusGained

    private void mailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTextFocusGained
        // TODO add your handling code here:
        if(mailText.getText().equals("Enter your email address") || mailText.getText().equals("Invalid Email !")){
            mailText.setText("");
        }
        mailText.setForeground(Color.BLACK);
    }//GEN-LAST:event_mailTextFocusGained

    private void c_nameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameTextFocusGained
        // TODO add your handling code here:
        if(c_nameText.getText().equals("Enter your company's name") || mailText.getText().equals("Enter a valid company name !")){
            c_nameText.setText("");
        }
        c_nameText.setForeground(Color.BLACK);
    }//GEN-LAST:event_c_nameTextFocusGained

    private void c_nameAddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameAddrFocusGained
        // TODO add your handling code here:
        if(c_nameAddr.getText().equals("Enter company's address") || c_nameAddr.getText().equals("Enter a valid company address !")){
            c_nameAddr.setText("");
        }
        c_nameAddr.setForeground(Color.BLACK);
    }//GEN-LAST:event_c_nameAddrFocusGained

    private void mob_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mob_noFocusGained
        // TODO add your handling code here:
        if(mob_no.getText().equals("Enter your mobile number") || mob_no.getText().equals("Enter valid mobile number !")){
            mob_no.setText("");
        }
        mob_no.setForeground(Color.BLACK);
    }//GEN-LAST:event_mob_noFocusGained

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals("Enter your username") || username.getText().equals("Username Cannot Be Empty !")){
            username.setText("");
        }
        username.setForeground(Color.BLACK);
    }//GEN-LAST:event_usernameFocusGained

    private void OTP_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OTP_textFocusGained
        // TODO add your handling code here:
        if(OTP_text.getText().equals("Enter your 6-digit OTP")){
            OTP_text.setText("");
        }
        OTP_text.setForeground(Color.BLACK);
    }//GEN-LAST:event_OTP_textFocusGained

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        if(passField.getText().equals("Enter pass")){
            passField.setText("");
        }
        passField.setForeground(Color.BLACK);
    }//GEN-LAST:event_passFieldFocusGained

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFocusLost
        // TODO add your handling code here:
        if(nameText.getText().equals("")){
            nameText.setText("Enter your full name");
            nameText.setForeground(gray);
        }
    }//GEN-LAST:event_nameTextFocusLost

    private void mailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailTextFocusLost
        // TODO add your handling code here:
        if(mailText.getText().equals("")){
            mailText.setText("Enter your email address");
            mailText.setForeground(gray);
        }
    }//GEN-LAST:event_mailTextFocusLost

    private void c_nameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameTextFocusLost
        // TODO add your handling code here:
        if(c_nameText.getText().equals("")){
            c_nameText.setText("Enter your company's name");
            c_nameText.setForeground(gray);
        }
    }//GEN-LAST:event_c_nameTextFocusLost

    private void c_nameAddrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c_nameAddrFocusLost
        // TODO add your handling code here:
        if(c_nameAddr.getText().equals("")){
            c_nameAddr.setText("Enter company's address");
            c_nameAddr.setForeground(gray);
        }
    }//GEN-LAST:event_c_nameAddrFocusLost

    private void mob_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mob_noFocusLost
        // TODO add your handling code here:
        if(mob_no.getText().equals("")){
            mob_no.setText("Enter your mobile number");
            mob_no.setForeground(gray);
        }
    }//GEN-LAST:event_mob_noFocusLost

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")){
            username.setText("Enter your username");
            username.setForeground(gray);
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        // TODO add your handling code here:
        if(passField.getText().equals("")){
            passField.setText("Enter pass");
            passField.setForeground(gray);
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void OTP_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OTP_textFocusLost
        // TODO add your handling code here:
        if(OTP_text.getText().equals("")){
            OTP_text.setText("Enter your 6-digit OTP");
            OTP_text.setForeground(gray);
        }
    }//GEN-LAST:event_OTP_textFocusLost

    private void genOTP(){
        Pattern pattern = Pattern.compile("^(.+)@(.+)$");
        Matcher matcher = pattern.matcher(mailText.getText());
        if(!matcher.matches()){
                mailText.setText("Invalid Email !");
                mailText.setForeground(Color.RED);
        } else {
            timeOverClock.setText("00:40");
            Random r = new Random();
            number = r.nextInt(999999);
            Codewind.Send.mail("demodanger8@gmail.com", mailText.getText(), "1234567890@0", "OTP from MediGo", "Your OTP is "+Integer.toString(number));  
        }
    }
    
    
    Timer timer = new Timer();
    private void sendOtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseClicked
        // TODO add your handling code here:
        genOTP();   //insatntiate Timer class
        timer.scheduleAtFixedRate(
                new java.util.TimerTask(){
                    public void run(){
                        String strTimer = timeOverClock.getText();
                        if(strTimer.equals("00:00")){
                            number=0;
                            timeOverClock.setText("");
                            OTP_ExpiredDialogBox OEDB = new OTP_ExpiredDialogBox();
                            OEDB.setVisible(true);
                            timer.cancel();
                        } else {
                            int sec = Integer.valueOf(strTimer.split(":")[1])-1; 
                            timeOverClock.setText(String.join(":", strTimer.split(":")[0], sec<10 ? "0"+String.valueOf(sec) : String.valueOf(sec)));
                        }
                    }
                },
                0, //delay
                1000  //repeat after 1s
        );
    }//GEN-LAST:event_sendOtpMouseClicked

    private void goToLogin_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLogin_buttonMouseClicked
        // TODO add your handling code here:
        Login_form logf = new Login_form();
        logf.setVisible(true);
        dispose();
    }//GEN-LAST:event_goToLogin_buttonMouseClicked

    private void sendOtpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseEntered
        // TODO add your handling code here:
        Border bd = BorderFactory.createLineBorder(Color.decode("#F81E9A"), 3, true);
        sendOtp.setBorder(bd);
    }//GEN-LAST:event_sendOtpMouseEntered

    private void signUp_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUp_buttonMouseEntered
        // TODO add your handling code here:
        Border bd = BorderFactory.createLineBorder(Color.decode("#F81E9A"), 3, true);
        signUp_button.setBorder(bd);
    }//GEN-LAST:event_signUp_buttonMouseEntered

    private void sendOtpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendOtpMouseExited
        // TODO add your handling code here:
        sendOtp.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#F81E9A")));
    }//GEN-LAST:event_sendOtpMouseExited

    private void signUp_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUp_buttonMouseExited
        // TODO add your handling code here:
        signUp_button.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#F81E9A")));
    }//GEN-LAST:event_signUp_buttonMouseExited

    private void goToLogin_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLogin_buttonMouseEntered
        // TODO add your handling code here:
        goToLogin_button.setBorder(new SoftBevelBorder(BevelBorder.RAISED, Color.decode("#ffffff"), Color.decode("#999999")));
        goToLogin_button.setForeground(Color.decode("#F81E9A"));
        goToLogin_button.setBackground(Color.decode("#ffffff"));
    }//GEN-LAST:event_goToLogin_buttonMouseEntered

    private void goToLogin_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLogin_buttonMouseExited
        // TODO add your handling code here:
        goToLogin_button.setBorder(BorderFactory.createLineBorder(Color.decode("#F81E9A"), 4, true));
        goToLogin_button.setForeground(Color.decode("#ffffff"));
        goToLogin_button.setBackground(Color.decode("#F81E9A"));
    }//GEN-LAST:event_goToLogin_buttonMouseExited

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        String pass = passField.getText();
        if(jCheckBox1.isSelected()){
            if(pass.equals("") || pass.equals("Enter pass")){
                passField.setText("Enter pass");
                jCheckBox1.setSelected(false);
            } else {
                passField.setEchoChar((char)0);
                jCheckBox1.setText("Show");
            }
        } else {
            jCheckBox1.setText("Hide");
            passField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private static byte[] getSalt() throws NoSuchAlgorithmException {
        SecureRandom sr = new SecureRandom();
        byte[] salt = new byte[16];
        sr.nextBytes(salt);
        return salt;        
    } 
    
    public static String hashPass(String p, byte[] salt){
        String h_pass = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            md.update(salt);
            byte[] bytes = md.digest(p.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            h_pass = sb.toString();
            
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        return h_pass;
    }
    
    private void signUp_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUp_buttonMouseClicked
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^(.+)@(.+)$");
        Matcher matcher = pattern.matcher(mailText.getText());
        Pattern pass = Pattern.compile("^(?=.*[0-9])" + "(?=.*[a-z])(?=.*[A-Z])" + "(?=.*[@#$%^&+=])" + "(?=\\S+$).{8,20}$");
        Matcher passMatch = pass.matcher(String.valueOf(passField.getPassword()));
        if(nameText.getText().length() >0){
            if(matcher.matches()){
                if(c_nameText.getText().length() >0){
                    if(c_nameAddr.getText().length() >0){
                        if(mob_no.getText().length() == 10){
                            if(username.getText().length() >0){
                                if(String.valueOf(passField.getPassword()).length() >=8 && passMatch.matches()){
                                    if(OTP_text.getText().equals(Integer.toString(number))){
                                        if(GSTNO.getText().length() > 0){
                                            try {
                                                String url = "jdbc:mysql://localhost:3306/medical_system?autoReconnect=true&useSSL=false";
                                                Class.forName("com.mysql.jdbc.Driver");
                                                Connection conn = DriverManager.getConnection(url, "root", "");
                                                Statement st = conn.createStatement();

                                                String name = nameText.getText();
                                                String mail = mailText.getText();
                                                String c_name = c_nameText.getText();
                                                String c_addr = c_nameAddr.getText();
                                                String mob = mob_no.getText();
                                                String user = username.getText();
                                                byte[] salt;
                                                try {
                                                    salt = getSalt();
                                                } catch (NoSuchAlgorithmException e) {
                                                    throw new RuntimeException(e);
                                                }
                                                BigInteger bi =new BigInteger(salt);
                                                String pSalt = bi.toString(2);
                                                String password = hashPass(String.valueOf(passField.getPassword()), salt);


                                                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                                                Calendar cal = Calendar.getInstance();
                                                String fy_from = sdf.format(cal.getTime());
                                                cal.add(Calendar.YEAR, 1);
                                                String fy_to = sdf.format(cal.getTime());

                                                String query = "Insert into user_table values(0, '"+user+"', '"+name+"', '"+mail+"', '"+c_name+"', '"+c_addr+"', '"+GSTNO.getText()+"', '"+fy_from+"', '"+fy_to+"', '"+mob+"', '"+password+"', '"+pSalt+"')";

                                                st.executeUpdate(query);

                                                // Popup account verification
                                                timer.cancel();
                                                AccountCreatedDialog A = new AccountCreatedDialog();
                                                A.setVisible(true);

                                                //close database server
                                                conn.close();

                                            } catch (Exception e){
                                                System.out.println(e);
                                            }
                                        } else {
                                            GSTNO.setText("Enter a valid GST number !");
                                            GSTNO.setForeground(Color.RED);
                                        }
                                    }  else {
                                        Invalid_OTP I = new Invalid_OTP();
                                        I.setVisible(true);
                                    }
                                } else {
                                    Invalid_pass_dialog p = new Invalid_pass_dialog();
                                    p.setVisible(true);
                                }
                            } else {
                                username.setText("Username Cannot Be Empty !");
                                username.setForeground(Color.RED);
                            }
                        } else {
                            mob_no.setText("Enter valid mobile number !");
                            mob_no.setForeground(Color.RED);
                        }
                    } else {
                        c_nameAddr.setText("Enter a valid company address !");
                        c_nameAddr.setForeground(Color.RED);
                    }
                } else {
                    c_nameText.setText("Enter a valid company name !");
                    c_nameText.setForeground(Color.RED);
                }
            } else {
                mailText.setText("Invalid Email !");
                mailText.setForeground(Color.RED);
            }
        } else {
            nameText.setText("Invalid Name !");
            nameText.setForeground(Color.RED);
        }
    }//GEN-LAST:event_signUp_buttonMouseClicked

    private void goToLogin_buttonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goToLogin_buttonFocusGained
        // TODO add your handling code here:
        goToLogin_button.setForeground(Color.decode("#F81E9A"));
        goToLogin_button.setBackground(Color.WHITE);
    }//GEN-LAST:event_goToLogin_buttonFocusGained

    private void goToLogin_buttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goToLogin_buttonFocusLost
        // TODO add your handling code here:
        goToLogin_button.setForeground(Color.WHITE);
        goToLogin_button.setBackground(Color.decode("#F81E9A"));
    }//GEN-LAST:event_goToLogin_buttonFocusLost

    private void GSTNOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GSTNOFocusGained
        // TODO add your handling code here:
        if(GSTNO.getText().equals("Enter your GST number") || GSTNO.getText().equals("Enter valid GST number !")){
            GSTNO.setText("");
        }
        GSTNO.setForeground(Color.BLACK);
    }//GEN-LAST:event_GSTNOFocusGained

    private void GSTNOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GSTNOFocusLost
        // TODO add your handling code here:
        if(GSTNO.getText().equals("")){
            GSTNO.setText("Enter your GST number");
            GSTNO.setForeground(gray);
        }
    }//GEN-LAST:event_GSTNOFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GSTNO;
    private javax.swing.JTextField OTP_text;
    private javax.swing.JTextArea c_nameAddr;
    private javax.swing.JTextField c_nameText;
    private javax.swing.JButton goToLogin_button;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mailText;
    private javax.swing.JTextField mob_no;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton sendOtp;
    private javax.swing.JButton signUp_button;
    private javax.swing.JLabel timeOverClock;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
